let rowsData = [
  {
    hr: "12:00 AM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "12:30 AM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "01:00 AM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "01:30 AM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "02:00 AM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "02:30 AM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "03:00 AM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "03:30 AM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "04:00 AM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "04:30 AM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "05:00 AM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "05:30 AM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "06:00 AM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "06:30 AM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "07:00 AM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "07:30 AM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "08:00 AM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "08:30 AM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "09:00 AM",
    tomi: "",
    felix: "",
    magi: {
      test: "",
    },
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "09:30 AM",
    tomi: "",
    felix: "",
    magi: {
      test: "",
    },
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "10:00 AM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "10:30 AM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "11:00 AM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "11:30 AM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "12:00 PM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "12:30 PM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "01:00 PM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "01:30 PM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "02:00 PM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "02:30 PM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "03:00 PM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "03:30 PM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "04:00 PM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "04:30 PM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "05:00 PM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "05:30 PM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "06:00 PM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "06:30 PM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "07:00 PM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "07:30 PM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "08:00 PM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "08:30 PM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "09:00 PM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "09:30 PM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "10:00 PM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "10:30 PM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "11:00 PM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
  {
    hr: "11:30 PM",
    tomi: "",
    felix: "",
    magi: "",
    arturo: "",
    mimi: "",
    isSelected: false,
  },
];

const genarateRowsServices = (duracion, servicio) => {
  let counter = duracion / 30 - 1;
  let rowsToAdd = [servicio];

  while (counter > 0) {
    const refService = rowsToAdd[rowsToAdd.length-1];
    const {rowIndex} = refService
    rowsToAdd.push({ ...refService, rowIndex: rowIndex + 1 });
    counter--;
  }

  return rowsToAdd;
};

const services = genarateRowsServices(120, {
  rowIndex: 17,
  estilista: "magi",
  servicio: "Corte de cabello H",
  hora: "09:00 AM",
  duracion: 120,
  cellID: "17-magi",
});

  const updateRows = (cita) => {
    const {services} = cita
    let currentData = rowsData
    services.forEach(service => {
      const {rowIndex} = service
      const {estilista} = service
      let rowToModify = currentData[rowIndex]
      rowToModify[estilista] = cita      
    });
  };

updateRows(services)

console.log(rowsData);
